<?php
$url = $this->url('main', array('lang'=>$this->lang));
//handle parameter get <span class="wp-smiley emoji emoji-smile" title=":)">:)</span>
$parameterGet = $this->Requesthelper();
if ($parameterGet != ""){
  $parameterGet = "?".$parameterGet;
}
?>
 
<?php if ($this->pageCount): ?>
<div class="paginationControl">
    <p>
        <!--<div style="float:left">-->
      <!-- Previous page link -->
      <ul class="pagination">
      <li><a href="<?= $url.'/1'; ?>">&laquo;</a></li>
      <?php foreach ($this->pagesInRange as $page): ?>
      <?php if ($page != $this->current): ?>
        <li><a class="nopage" href="<?= $url.'/'.$page.$parameterGet; ?>">
      <?= $page; ?>
      </a></li>
      <?php else: ?>
            <li><a class="nopage" href="<?= $url.'/'.$page.$parameterGet; ?>">
      <?= $page; ?>
      </a></li>
    </span>
      
      <?php endif; ?>
      <?php endforeach; ?>
      <li><a class="next" href="<?= $url.'/'.$this->pageCount.$parameterGet; ?>">&raquo;</a></li>
      </ul>
    </p>
</div>
<?php endif; ?>