<div class="loginContainer">
<?php
	$form = $this -> form;
	$form->setAttribute('action', $this->url(
	    'login',
	    array(
	        'action' => 'login',
	    )
	));
	$form -> prepare();
	echo $this->form()->openTag($form);
?>
<div id='formContainer'>
	<div class="row">
		<?php
		  	echo $this -> formLabel($form -> get('username'));
			echo $this -> formElement($form -> get('username'));
		?>
		<br>
	  	<?php
			echo $this -> formLabel($form -> get('password'));
			echo $this -> formElement($form -> get('password'));
		?>
		<br>
	  	<?php
	  		echo $this -> formElement($form -> get('btnSubmit'));
	  	?>
	</div>
	<?php
		
		if ($this -> messages) {
			foreach ($this->messages as $message) {
				echo "<h5 style='color:red;'>";
				echo $message;
				echo "<BR>";
				echo "</h5>";
			}
		}
		echo "<br>";
		echo $this -> formElementErrors($form -> get('username'));
		echo "<br>";
		echo $this -> formElementErrors($form -> get('password'));
	?>
</div>

<?php
	echo $this->form()->closeTag($form);
?>
</div>
